# fly.toml app configuration file generated for codexify on 2023-05-17T17:24:14-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "codexify"
primary_region = "lax"

[http_service]
  internal_port = 6000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
